# This is a basic workflow to help you get started with Actions

name: deploy-notebook

# Run this when the main branch changes
on:
	push:
		branches:
		- main

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
	deploy-book:
		runs-on: ubuntu-latest
		permissions:
			pages: write
			id-token: write
		steps:
		- uses: actions/checkout@v3

		# Install dependencies
		- name: Set up Python 3.9
			uses: actions/setup-python@v4
			with:
				python-version: 3.9

		# Build
		- name: Build
			run: |
				jupyter-book build src/notebooks/Viz*.ipynb

		# Upload the book's HTML as an artifact
		- name: Upload artifact
			uses: actions/upload-pages-artifact@v2
			with:
				path: "build/html"

		# Deploy the book's HTML to GitHub Pages
		- name: Deploy to GitHub Pages
			id: deployment
			uses: actions/deploy-pages@v2
